services:

  #Postgres Database
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: autoreach
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  # FastAPI backend
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
      - ./backend/.env
    volumes:
      - chroma_data:/app/chroma_db

  #  Next.js frontend  
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"

volumes:
  chroma_data: