import os
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

# ─── Load .env ─────────────────────────────────────────────────
# Handle both local standalone and docker-compose execution paths
for env_path in [
    os.path.join(os.path.dirname(os.path.abspath(__file__)), ".env"),
    os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), ".env"),
    "/.env",
]:
    if os.path.exists(env_path):
        with open(env_path) as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    key, val = line.split("=", 1)
                    os.environ[key.strip().strip("'\"")] = val.strip().strip("'\"")
        break

def send_fftc_email(manager_email, subject, email_body):
    # 1. Your Configuration from Environment Variables
    sender_email = os.environ.get("SENDER_EMAIL", "aaryan.biradar06@gmail.com")
    app_password = os.environ.get("APP_PASSWORD")

    if not app_password:
        print("[!] Failed to send email: APP_PASSWORD not found in environment")
        return

    # 2. Build the Email
    msg = MIMEMultipart()
    msg['From'] = f"Alex (Food for the Capital) <{sender_email}>"
    msg['To'] = manager_email
    msg['Subject'] = subject

    # Attach the dynamic text generated by your LLM
    msg.attach(MIMEText(email_body, 'plain'))

    server = None
    try:
        # 3. Connect to Gmail's SMTP Server
        print(f"Connecting to email server for {manager_email}...")
        server = smtplib.SMTP('smtp.gmail.com', 587)
        server.starttls() # Secure the connection
        
        # 4. Login and Send
        server.login(sender_email, app_password)
        server.send_message(msg)
        print(f"[OK] Success! Follow-up email sent to {manager_email}")
        
    except Exception as e:
        print(f"[!] Failed to send email: {e}")
        
    finally:
        # 5. Always close the connection
        if server:
            server.quit()